name: Circuits
on: [ push, pull_request ]
jobs:
  test:
    name: Circuits tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install c dependencies
      run: |
        sudo apt install -y nlohmann-json3-dev
        sudo apt install -y nasm
    - name: Download circom
      run: |
        mkdir -p $HOME/bin
        curl -sSfL https://github.com/iden3/circom/releases/download/v2.1.2/circom-linux-amd64 -o $HOME/bin/circom
        chmod +x $HOME/bin/circom
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: run tests
      run: |
        cd circuits
        npm cache clean --force
        npm install
        npm run test
